### ISSUE TITLE
Dropwizard metrics are not exported in simpleclient_vertx or simpleclient_vertx4

### ISSUE THREAD

**Issue by yaronel** [prometheus/client_java#780]
Using [DropwizardExports](https://github.com/prometheus/client_java/blob/master/simpleclient_dropwizard/src/main/java/io/prometheus/client/dropwizard/DropwizardExports.java) doesn't work with neither [simpleclient_vertx](https://github.com/prometheus/client_java/blob/master/simpleclient_vertx/src/main/java/io/prometheus/client/vertx/MetricsHandler.java) nor [simpleclient_vertx4](https://github.com/prometheus/client_java/blob/master/simpleclient_vertx4/src/main/java/io/prometheus/client/vertx/MetricsHandler.java).

The Vertx handler calls [`CollectorRegistry.filteredMetricFamilySamples`](https://github.com/prometheus/client_java/blob/master/simpleclient/src/main/java/io/prometheus/client/CollectorRegistry.java#L139) which returns an enumeration of collectors from `CollectorRegistry.namesToCollectors`. 

DropwizardExports implements `Collector.Describable` but it's [`describe`](https://github.com/prometheus/client_java/blob/master/simpleclient_dropwizard/src/main/java/io/prometheus/client/dropwizard/DropwizardExports.java#L198) method returns an empty `List<MetricFamilySamples>` so nothing is added to the `CollectorRegistry.namesToCollectors` [when it's registered](https://github.com/prometheus/client_java/blob/master/simpleclient/src/main/java/io/prometheus/client/CollectorRegistry.java#L108). However, the empty list of names does get added to [`CollectorRegistry.collectorsToNames`](https://github.com/prometheus/client_java/blob/master/simpleclient/src/main/java/io/prometheus/client/CollectorRegistry.java#L63) which is how I was able to go around this issue for the time being.

Right now the only way I was able to export the Dropwizard metrics was by calling [`CollectorRegistry.metricFamilySamples`](https://github.com/prometheus/client_java/blob/master/simpleclient/src/main/java/io/prometheus/client/CollectorRegistry.java#L128) which uses the `CollectorRegistry.collectorsToNames`.

**Comment by fstab** [comment]
:+1: thanks for reporting. I implemented a fix in #785, but didn't test it yet. Would you mind to have a look?

**Comment by yaronel** [comment]
@fstab Hey, sorry I didn't get a notification so only seeing your comment now.
I checked it and it still doesn't work.
I left a comment on PR #785 - https://github.com/prometheus/client_java/pull/785/files#r893215571
